FROM nginx:alpine

ARG TEAM="slsa-lab-green"
ARG COLOR="#2E7D32"

LABEL maintainer="slsa-lab@example.com"
LABEL team=${TEAM}

RUN apk update && apk upgrade --no-cache

RUN mkdir -p /usr/share/nginx/html

COPY green.html /usr/share/nginx/html/index.html

RUN sed -i 's/listen\s\+80;/listen 8080;/g' /etc/nginx/conf.d/default.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
