name: Build and Push Image

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'back1ash' || 
      github.actor == 'gaeul3303' ||
      github.actor == 'KimYe-Ji'
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/application
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU and buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ github.run_number }}
            ${{ env.IMAGE }}:sha-${{ github.sha }}
          build-args: |
            TEAM=${{ github.repository_owner }}
            COLOR=${{ secrets.TEAM_COLOR }}
            
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: '${{ env.IMAGE }}@${{ steps.push.outputs.digest }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: 1

      - name: Update k8s manifest with new image tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          sed -i "s|image: .*|image: ${{ env.IMAGE }}:sha-${{ github.sha }}|" k8s/deployment.yaml
          git add k8s/deployment.yaml
          git commit -m "ci: update verified image to sha-${{ github.sha }}"
          git push